# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeexec < Formula
  desc "FZF-based kubectl exec into pods"
  homepage "https://github.com/estebanmilaho/kubeexec"
  version "0.0.12"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.12/kubeexec_0.0.12_darwin_amd64.tar.gz"
      sha256 "39072224019bba5eb9219152ae4eec96ba02a96c954fa4903d61c2e316742275"

      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
    on_arm do
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.12/kubeexec_0.0.12_darwin_arm64.tar.gz"
      sha256 "b08ed92d4d8cf44ce0d2d038737f0d0b6b93ab23835927d18bdd28ae60ed0fb8"

      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.12/kubeexec_0.0.12_linux_amd64.tar.gz"
        sha256 "95d75d708cf84ecf5d8109b1ec7fd30648e6d25e410492cb1e4df97173fbb652"

        def install
          bin.install "kubeexec"
          bash_completion.install "completion/kubeexec.bash" => "kubeexec"
          zsh_completion.install "completion/_kubeexec"
          fish_completion.install "completion/kubeexec.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.12/kubeexec_0.0.12_linux_arm64.tar.gz"
        sha256 "f42336548bbadb57bd5add7d36f44f130f4621a1c26271a53fcce1c45f810f3e"

        def install
          bin.install "kubeexec"
          bash_completion.install "completion/kubeexec.bash" => "kubeexec"
          zsh_completion.install "completion/_kubeexec"
          fish_completion.install "completion/kubeexec.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/kubeexec", "-version"
  end
end
