# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeexec < Formula
  desc "FZF-based kubectl exec into pods"
  homepage "https://github.com/estebanmilaho/kubeexec"
  version "0.0.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.8/kubeexec_0.0.8_darwin_amd64.tar.gz"
      sha256 "75cdbc91adb660708b6b7ba42a65d431c8193f5e74148e730752efab176e4126"

      def install
        bin.install "kubeexec"
      end
    end
    on_arm do
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.8/kubeexec_0.0.8_darwin_arm64.tar.gz"
      sha256 "980e85a5686a0ff539371cde49b8e6ee1d9d9b7b99e3063d29cfc26277dc96b3"

      def install
        bin.install "kubeexec"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.8/kubeexec_0.0.8_linux_amd64.tar.gz"
        sha256 "a5f40c5dda624bf6e9787778807dc98f9a3710b5ade3da83fc039ffd49d9f70b"

        def install
          bin.install "kubeexec"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.8/kubeexec_0.0.8_linux_arm64.tar.gz"
        sha256 "2af98a4f5a4e1eb5b45513cb7c1c64e3d162640fba20c5286e9fb6cddf2c1811"

        def install
          bin.install "kubeexec"
        end
      end
    end
  end

  test do
    system "#{bin}/kubeexec", "-version"
  end
end
