# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeexec < Formula
  desc "FZF-based kubectl exec into pods"
  homepage "https://github.com/estebanmilaho/kubeexec"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.18/kubeexec_0.0.18_darwin_amd64.tar.gz"
      sha256 "7349c80d10135bac642ece721578d0f94b9791da4564b3d1c244b4d3eb0bfebc"

      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.18/kubeexec_0.0.18_darwin_arm64.tar.gz"
      sha256 "68417f861f25f95ad3f0360c4d1754fc98fe824c43834972f23f621360c0a1e9"

      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.18/kubeexec_0.0.18_linux_amd64.tar.gz"
      sha256 "cde34a2ffdbcd66971f2e3dc771b59e605e00a51276ae0688ed1e7962ce29d38"
      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/estebanmilaho/kubeexec/releases/download/v0.0.18/kubeexec_0.0.18_linux_arm64.tar.gz"
      sha256 "b89b72fb686cb46fbcdd5c6816de4f1a1a7eaf8f2767e99e97c86b9a72babeac"
      def install
        bin.install "kubeexec"
        bash_completion.install "completion/kubeexec.bash" => "kubeexec"
        zsh_completion.install "completion/_kubeexec"
        fish_completion.install "completion/kubeexec.fish"
      end
    end
  end

  test do
    system "#{bin}/kubeexec", "-version"
  end
end
